export const THEMES_LOADING_STARTED = 'THEMES_LOADING_STARTED';
export const THEMES_LOADING_SUCCEED = 'THEMES_LOADING_SUCCEED';
export const THEMES_LOADING_FAILED = 'THEMES_LOADING_FAILED';

export const APPLY_THEME = 'APPLY_THEME';

export const COLUMNS_LOADING_STARTED = 'COLUMNS_LOADING_STARTED';
export const COLUMNS_LOADING_SUCCEED = 'COLUMNS_LOADING_SUCCEED';
export const COLUMNS_LOADING_FAILED = 'COLUMNS_LOADING_FAILED';

export const ORDERS_LOADING_STARTED = 'ORDERS_LOADING_STARTED';
export const ORDERS_LOADING_SUCCEED = 'ORDERS_LOADING_SUCCEED';
export const ORDERS_LOADING_FAILED = 'ORDERS_LOADING_FAILED';

export const TOGGLE_FILTER_DETAIL = 'TOGGLE_FILTER_DETAIL';
export const TEXT_FILTER_CHANGED = 'TEXT_FILTER_CHANGED';